### ISSUE TITLE
Quick copy the team comp to paste elsewhere

### ISSUE THREAD

**Issue by axi92** [andrerfcsantos/overwatch-hero-picker#11]
We are playing random a lot and one of us have to write the comp every time in the chat.
Copy feature would make that easier.

**Comment by andrerfcsantos** [comment]
I think it's a good idea and I can add that.

Just to have a better idea of what you need, could the contents of the paste be something like:

```
TANKS

Roadhog
Reihardt

DAMAGE

Soldier: 75
Mei

SUPPORT

Mercy
Ana
```

Or would you rather have other format?

**Comment by axi92** [comment]
Just like this:

```
var all = $(".hero-name-squad").map(function() {
    return this.innerHTML;
}).get();
console.log(all.join());
```
Everybody knows whats tank or dps, all in one line to paste into ingame chat.

**Comment by andrerfcsantos** [comment]
@axi92 This is already in the live version, let me know what you think and if you want further changes :)

**Comment by axi92** [comment]
Nice looks good! @andrerfcsantos
